fix in source set compile task doFirst action definition used for semantic db configuration
cosmicsilence/gradle-scalafix pull request #59
Opened 2021-11-30 18:34 UTC by fsanjuan

Fix for https://github.com/cosmicsilence/gradle-scalafix/issues/58

2021-12-07 16:47 UTC, aishfenton commented
Not sure if you also want to look at this as part of it too. https://github.com/cosmicsilence/gradle-scalafix/issues/58#issuecomment-987490084

Thankfully the plugin option has an easy workaround (i.e. using Gradle's scalaCompilerPlugin mechanism instead of setting the option). But the `sourceroot` part is still puzzling me. I was hoping maybe it could just be removed (since according to the semanticdb docs, all it does is relativize the paths), but without it the generated `semenaticdb` files aren't even appearing in the build directory. So quite confused by that.

2021-12-15 10:05 UTC, fsanjuan commented
> Not sure if you also want to look at this as part of it too. [#58 (comment)](https://github.com/cosmicsilence/gradle-scalafix/issues/58#issuecomment-987490084)
> 
> Thankfully the plugin option has an easy workaround (i.e. using Gradle's scalaCompilerPlugin mechanism instead of setting the option). But the `sourceroot` part is still puzzling me. I was hoping maybe it could just be removed (since according to the semanticdb docs, all it does is relativize the paths), but without it the generated `semenaticdb` files aren't even appearing in the build directory. So quite confused by that.

👋 Apologies for the late reply. I just read your comments there :)

Let's keep this PR to upgrade the plugins and fix that conditional `doFirst` action. We will work on that in a new one :D

2021-12-15 19:57 UTC, marcelocenerine submitted a review, later dismissed

2021-12-15 22:12 UTC, marcelocenerine commented
could you take a look a this [comment](https://github.com/cosmicsilence/gradle-scalafix/issues/58#issuecomment-995246857) before merging this PR?

2021-12-16 12:12 UTC, marcelocenerine commented on src/main/groovy/io/github/cosmicsilence/scalafix/ScalafixPlugin.groovy
> +            sourceSet.compileTask.doFirst {
should we consider replacing the `doFirst` action with a "configure task" as suggested [here](https://docs.gradle.org/current/userguide/common_caching_problems.html#custom_actions)?

2021-12-19 22:47 UTC, marcelocenerine requested changes

2021-12-19 22:47 UTC, marcelocenerine commented on src/main/groovy/io/github/cosmicsilence/scalafix/ConfigureSemanticdbCompiler.groovy
> +class ConfigureSemanticdbCompiler extends DefaultTask {
`ConfigureSemanticdbTask`?

2021-12-19 22:47 UTC, marcelocenerine commented on src/main/groovy/io/github/cosmicsilence/scalafix/ScalafixPlugin.groovy
> +                        "configure${sourceSet.name.capitalize()}SemanticdbCompilerPlugin", ConfigureSemanticdbCompiler) { task ->
- `"configureSemanticdb${sourceSet.name.capitalize()}"`?
- let's add a group/description to it

2021-12-19 22:47 UTC, marcelocenerine commented on src/main/groovy/io/github/cosmicsilence/scalafix/ScalafixPlugin.groovy
> +            sourceSet.compileTask.dependsOn configureSemanticdbCompilerTask
could we have a comment here explaining why this is done inside `register` and not outside?

2021-12-19 22:47 UTC, marcelocenerine commented on src/test/groovy/io/github/cosmicsilence/scalafix/ScalafixPluginTest.groovy
> +            task.run()
I'm thinking if we could simplify some of these tests by introducing a test class for the new task and moving everything concerning the Semanticdb setup into it. Tests in this class would just check if the dependencies between tasks were created.
Also, there are some tests in `ScalafixPluginFunctionalTest` that may need to be updated

2023-11-03 22:19 UTC, marcelocenerine commented
Closing this PR since there's been no activity lately. I will resume the work in a new PR.

2023-11-03 22:19 UTC, closed without merging